extends Node

enum MatchmakingMode {
	RANDOM,
	PRIVATE_CREATE,
	PRIVATE_JOIN
}

enum PlayerRole {STRIPES = 1, SOLIDS}
enum GameType {EIGHT_BALL_MULTIPLAYER = 1, EIGHT_BALL_SINGLEPLAYER, CRAZY_EIGHT_BALL_MULTIPLAYER, CRAZY_EIGHT_BALL_SINGLEPLAYER}
